name: ploog
version: '${project.version}'
main: io.github.anishthewizard.ploog
api-version: '1.20'
# Replace "kit" with the name of your command.
commands:
  balls:
    description: idk
    usage: /balls